### PR TITLE
feat: add -T/--timestamps (env LOGPROXY_TIMESTAMPS) option to prepend strftime to each line

### PR DESCRIPTION
**Pull request by mk-fg**
Might work to address `[ ] option to add a timestamp before each log line` in the README.
Not sure if it's the best way to do it, but was easy enough to add this way, to address my own use-case.
Feel free to merge with any kind of edits and tweaks, preserving commit/attribution does not matter to me at all.

Thanks for making this small tool.
It's especially useful in modern non-shell invocations with a proper wrapper mode and configuration via env vars.

### CODE REVIEW

**Comment by thebaptiste** [comment]
Many thanks you for your PR. 
It works perfectly when the new option `-T` is used. But without this option, every log line starts with `(null)` !
It's because, in `spawn_logproxy_async`, with `-T \"%s\"`, the NULL value for `timestamp_prefix` is replaced by `(null)` and passed to log_proxy
Adding this test in `log_proxy` main fix the problem : 
`if ( strcmp( timestamp_prefix, "(null)" ) == 0 ) timestamp_prefix = NULL;`
I did'nt find any better way to fix it, so I will take your PR with this fix.

**Comment by mk-fg** [comment]
Thanks.

My bad wrt prefix arg, added an option to wrapper as an afterthought and didn't think to test it without prefix.
Other fix can probably be using something like `prefix_arg = timestamp_prefix ? "" : sprintf("-T \"%s\"", timestamp_prefix)` in the wrapper, and templating that into the command line.
And I think it'd be easier if wrapper wasn't using a string command, but an array of arguments, where such stuff can be appended or not as-needed, as also suggested in #37 for a different reason.

**Comment by thebaptiste** [comment]
I'm not the lead maintener of log_proxy (@thefab is very busy these days) and you're probably a better python developer than me !
So feel free to open any improvement PR.

Meantime I will release 0.6.0 with your new option (which by the way was in our roadmap since several years !)

Thanks again

**Comment by mk-fg** [comment]
It's C, not python, but yeah sure, I'll make a PR today or tomorrow.

**Comment by thebaptiste** [comment]
Yes C ! So I will wait your PR before releasing.

**Comment by mk-fg** [comment]
Created it as #38, which should address this issue and #37, as described there.

**Pull request merged**
