### PR TITLE
feat: add a chmod/chown/chgrp option

### PR DESCRIPTION
**Pull request by thefab**
Close: #21

### CODE REVIEW

**Comment by tomalok** [comment]
While an explicit `--chmod` is welcome, it doesn't address/solve the ownership issue (in my case, `root:docker`; FWIW, I haven't take a close look at the PR yet so I don't know offhand if a solution is in there).

I think an _implicit_ solution might be a little easier to do...  That is, when logs are rotated, `log_proxy` would `stat` the old log file and then ***TRY*** to `chmod` and `chown` the new log file to be the same.  If the user that `log_proxy` is running as does not have sufficient privileges to set either the mode or the ownership (i.e. the `chmod` or `chown` fails) that's okay, and move along (maybe emit a warning somewhere).

**Comment by tomalok** [comment]
the addition of `--chown` and `--chgrp` will satisfy my use case.

**Review by thebaptiste — APPROVED** [review]

**Comment by tomalok** [comment]
Can a new release be tagged so that I can build a new Alpine package?

**Comment by thefab** [comment]
Yes! Probably tomorrow! Thanks for the work you do for alpine users!

**Comment by thefab** [comment]
0.4 is out ;-)

**Pull request merged**
